# Generated by Django 5.1.1 on 2024-10-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'permissions': [('can_edit_article', 'Puede editar artículo'), ('can_delete_article', 'Puede eliminar artículo')]},
        ),
    ]
